CREATE USER 'airadmin' IDENTIFIED BY 'air@p0o9i8u7';
GRANT ALL PRIVILEGES ON *.* TO 'airadmin'@'%' IDENTIFIED BY 'air@p0o9i8u7' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'airadmin'@'localhost' IDENTIFIED BY 'air@p0o9i8u7' WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE DATABASE air_platform CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;